apiVersion: v1
kind: Template
metadata:
  name: maxscale-standalone
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${NAME}
  stringData:
    service-password: ${MAXSCALE_SERVICE_PW}
    monitor-password: ${MAXSCALE_MONITOR_PW}
- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
  spec:
    ports:
    - name: master-only
      port: 3306
      targetPort: 3306
    - name: read-write
      port: 3307
      targetPort: 3307
    selector:
      name: ${NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}
  spec:
    replicas: ${{REPLICA_COUNT}}
    selector:
      name: ${NAME}
    template:
      metadata:
        labels:
          name: ${NAME}
        name: ${NAME}
      spec:
        containers:
        - name: maxscale
          image: docker.io/appuio/maxscale-docker:2.2.1-beta-4
          env:
          - name: MASTER_ONLY_LISTEN_ADDRESS
            value: 0.0.0.0
          - name: READ_WRITE_LISTEN_ADDRESS
            value: 0.0.0.0
          - name: DB1_ADDRESS
            value: ${DB1_ADDRESS}
          - name: DB2_ADDRESS
            value: ${DB2_ADDRESS}
          - name: DB3_ADDRESS
            value: ${DB3_ADDRESS}
          - name: SERVICE_PWD
            valueFrom:
              secretKeyRef:
                name: ${NAME}
                key: service-password
          - name: MONITOR_PWD
            valueFrom:
              secretKeyRef:
                name: ${NAME}
                key: monitor-password
          ports:
          - name: master-only
            containerPort: 3306
          - name: read-write
            containerPort: 3307
          livenessProbe:
            tcpSocket:
              port: master-only
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            tcpSocket:
              port: master-only
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 128Mi
    triggers:
    - type: ConfigChange
parameters:
- description: The name assigned to all of the objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: maxscale
- description: The password for the maxscale service user
  name: MAXSCALE_SERVICE_PW
  required: true
- description: The password for the maxscale monitor user
  name: MAXSCALE_MONITOR_PW
  required: true
- description: The for the first backend DB
  name: DB1_ADDRESS
  required: true
- description: The for the second backend DB
  name: DB2_ADDRESS
  required: true
- description: The for the third backend DB
  name: DB3_ADDRESS
  required: true
- description: Number of replicas
  name: REPLICA_COUNT
  value: "2"
  required: true
